import AppKit
import Carbon.HIToolbox

/// Inserts recognized text into the frontmost app.
/// Default method is `paste`: stash the clipboard → write our text → wait for the dictation
/// modifiers to be released → ⌘V → restore the clipboard. This is far more reliable than
/// per-character key synthesis for long/multilingual text (mirrors FreeFlow / Wispr Flow),
/// and avoids the "text not inserted / focus jumps to Dock" failure of typing while a
/// modifier is still held.
enum TextInserter {
    static func insert(_ text: String, method: InsertMethod) {
        let t = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !t.isEmpty else { return }
        switch method {
        case .type:  CursorTyping.type(t)
        case .paste: paste(t)
        }
    }

    // MARK: - Clipboard paste

    private static func paste(_ text: String) {
        let pb = NSPasteboard.general
        let saved = snapshot(pb)

        pb.clearContents()
        pb.setString(text, forType: .string)
        // Transient markers so clipboard managers (Maccy, Raycast, Paste, …) skip this entry.
        for t in transientTypes { pb.setString("", forType: t) }
        let writtenChange = pb.changeCount

        DispatchQueue.global(qos: .userInitiated).async {
            waitForModifiersReleased()       // never ⌘V while Fn/Shift is still held
            usleep(30_000)
            postCmdV()
            usleep(120_000)                  // let the target app consume the paste
            DispatchQueue.main.async { restore(saved, to: pb, ifChangeCount: writtenChange, wrote: text) }
        }
    }

    private static let transientTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("de.petermaurer.TransientPasteboardType"),
    ]

    private static func snapshot(_ pb: NSPasteboard) -> [[NSPasteboard.PasteboardType: Data]] {
        (pb.pasteboardItems ?? []).map { item in
            var dict: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types { if let data = item.data(forType: type) { dict[type] = data } }
            return dict
        }
    }

    /// Restore the saved clipboard — but only if it still holds exactly what we wrote (or
    /// nothing changed), so we never clobber something the user copied in the meantime.
    private static func restore(_ saved: [[NSPasteboard.PasteboardType: Data]],
                                to pb: NSPasteboard, ifChangeCount expected: Int, wrote: String) {
        let stillOurs = pb.string(forType: .string) == wrote
        guard pb.changeCount == expected || stillOurs else { return }
        pb.clearContents()
        let items: [NSPasteboardItem] = saved.map { entry in
            let item = NSPasteboardItem()
            for (type, data) in entry { item.setData(data, forType: type) }
            return item
        }
        if !items.isEmpty { pb.writeObjects(items) }
    }

    private static func waitForModifiersReleased(maxWaitMs: Int = 800) {
        let relevant: NSEvent.ModifierFlags = [.command, .shift, .control, .option, .function]
        var waited = 0
        while !NSEvent.modifierFlags.isDisjoint(with: relevant), waited < maxWaitMs {
            usleep(20_000); waited += 20
        }
    }

    private static func postCmdV() {
        let src = CGEventSource(stateID: .combinedSessionState)
        let v = CGKeyCode(kVK_ANSI_V)
        let down = CGEvent(keyboardEventSource: src, virtualKey: v, keyDown: true)
        down?.flags = .maskCommand
        let up = CGEvent(keyboardEventSource: src, virtualKey: v, keyDown: false)
        up?.flags = .maskCommand
        down?.post(tap: .cgSessionEventTap)
        up?.post(tap: .cgSessionEventTap)
    }
}
